### ISSUE TITLE
Missing flags

### ISSUE THREAD

**Issue by mrIliya** [AnisTigrini/country-flags#1]
Hi, can you add missing flags of Kyrgyzstan, Antarctica, and Bouvet Island

**Comment by AnisTigrini** [comment]
Will do, also if you want you can submit a PR :)

**Comment by AnisTigrini** [comment]
@mrIliya I did add Antartica (non official) with flag : https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg/220px-Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg.png

Kyrgyzstan is already present. 
Bouvet island seems to use the same flag as Norway you might be able to arrange your code to point out to the norwegian flag.

The new version is @1.0.3
