### ISSUE TITLE
Kazakhstan Flag is Broken

### ISSUE THREAD

**Issue by AmirBoukerTHM** [AnisTigrini/country-flags#2]
Using V1.0.3 all the flags seems Okey but the flag of Kyrgyzstan 
![image](https://github.com/AnisTigrini/country-flags/assets/171350737/e4b58891-bb49-48c0-b4e6-88970bb32364)

**Comment by AnisTigrini** [comment]
Thanks for pointing it out. It should be corrected in the afternoon.

**Comment by samdemaeyer** [comment]
@AnisTigrini. I created a PR to fix this flag. 
Please have a look and potentially release #3

**Comment by AnisTigrini** [comment]
Thanks @samdemaeyer @AmirBoukerTHM .
I just pushed a new package on NPM.
Let me know for anything.
